name: "Terraform LocalStack CI - aponti-desafio6"

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  terraform-deploy:
    name: "Terraform Init, Plan & Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Sobe o LocalStack com a Action oficial e a variável de aceite exigida
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          install-awslocal: false
          auth-token: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        env:
          LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT: "1"
          SERVICES: "s3,ec2"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform